[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ptn-set-transformer"
version = "0.1.0"
authors = [{ name = "Cody Martin", email = "codycmar10@gmail.com" }]
description = "Training and inference on protein sets (genomes)"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "torch>=2",
    "transformers",
    "jsonargparse[signatures]",
    "lightning>=2",
    "tables",
    "torch_geometric",
    "pandas",
    "more-itertools",
]

[project.scripts]
pst = "pst:main.main"

[project.urls]
"Homepage" = "https://github.com/cody-mar10/protein_set_transformer"
"Bug Tracker" = "https://github.com/cody-mar10/protein_set_transformer/issues"
