
# MODEL hparams
[[hparams]]
name = "complexity"
suggest = "categorical"
choices = ["small_1", "small_2", "medium_1", "medium_2", "large_1", "large_2"]

# this refers to the previous table entry in the hparams arraytable, ie complexity
[hparams.map]
small_1 = { num_heads = 2, n_enc_layers = 2 }
small_2 = { num_heads = 2, n_enc_layers = 3 }
medium_1 = { num_heads = 4, n_enc_layers = 4 }
medium_2 = { num_heads = 4, n_enc_layers = 5 }
large_1 = { num_heads = 8, n_enc_layers = 8 }
large_2 = { num_heads = 8, n_enc_layers = 10 }

[[hparams]]
name = "embed_scale"
suggest = "categorical"
choices = [1, 2, 4, 8]

[[hparams]]
name = "dropout"
suggest = "float"
low = 0.0
high = 0.5
log = false

# OPTIMIZER hparams
[[hparams]]
name = "lr"
suggest = "float"
low = 5e-4
high = 5e-2
log = true
parent = "optimizer"

[[hparams]]
name = "weight_decay"
suggest = "float"
low = 1e-3
high = 1e-1
log = true
parent = "optimizer"

# DATA hparams
[[hparams]]
name = "batch_size"
suggest = "categorical"
choices = [16, 32]
parent = "data"

[[hparams]]
name = "chunk_size"
suggest = "int"
low = 15
high = 50
step = 5
parent = "data"

# LOSS hparams
[[hparams]]
name = "margin"
suggest = "float"
low = 0.1
high = 10.0
log = true
parent = "loss"

# EXPERIMENT hparams
# [[hparams]]
# name = "swa_epoch_start"
# suggest = "float"
# low = 0.5
# high = 0.8
# log = false

# [[hparams]]
# name = "annealing_epochs"
# suggest = "int"
# low = 10
# high = 100
# step = 1

# [[hparams]]
# name = "annealing_strategy"
# suggest = "categorical"
# choices = ["linear", "cosine"]

# AUGMENTATION hparams
[[hparams]]
name = "sample_scale"
suggest = "float"
low = 1.0
high = 15.0
log = false
parent = "augmentation"

[[hparams]]
name = "sample_rate"
suggest = "float"
low = 0.25
high = 0.75
log = false
parent = "augmentation"
